##RheaKVStoreOptions
---
clusterName: rhea_benchmark

placementDriverOptions:
  fake: true
  hashRoute: true

storeEngineOptions:
  storageType: PMem
  rocksDBOptions:
    fastSnapshot: true
    dbPath: rhea_benchmark_db
  pmemDBOptions:
    dbPath: /mnt/mem/rhea_benchmark_db
  raftDataPath: /mnt/mem/rhea_benchmark_raft_data
  raftRpcCoreThreads: 128
  serverAddress:
    ip: 127.0.0.1
    port: 18091
  commonNodeOptions:
    raftOptions:
      readOnlyOptions: ReadOnlyLeaseBased
  regionEngineOptionsList:
    - { regionId: 1, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }
    - { regionId: 2, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }
    - { regionId: 3, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }
    - { regionId: 4, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }
    - { regionId: 5, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }
    - { regionId: 6, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }
    - { regionId: 7, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }
    - { regionId: 8, nodeOptions: { electionTimeoutMs: 10000, raftOptions: { sync: false} } }

onlyLeaderRead: true

failoverRetries: 1
futureTimeoutMillis: 5000
useParallelKVExecutor: false

